version: '3'
services:
  redis:
    build: ./redis
    container_name: ${PROJECT_NAME}-redis
    image: 'redis:6.0.5'
    ports:
      - '6379:6379'
    networks:
      - net

  php:
    build: ./api
    container_name: ${PROJECT_NAME}-php
    ports:
      - '9000:9000'
    volumes:
      - ./api:/var/www/api
    depends_on:
      - redis
    links:
      - redis:${PROJECT_NAME}-redis
    networks:
      - net

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./api:/var/www/api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - net

  flutter:
    build: ./frontend
    container_name: ${PROJECT_NAME}-flutter
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/app
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php:${PROJECT_NAME}-php
    networks:
      - net

networks:
  net:
    driver: bridge