<?php

namespace App\Tests\util;

use Liip\FunctionalTestBundle\Test\WebTestCase;
use Symfony\Component\Dotenv\Dotenv;

class CustomWebTestCase extends WebTestCase
{
    protected function setUp(): void
    {
        (new Dotenv())->usePutenv()->bootEnv(dirname(__DIR__) . '/../.env.test');
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}