<?php

namespace App\Tests\util;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Dotenv\Dotenv;

class CustomTestCase extends TestCase
{
    protected function setUp(): void
    {
        (new Dotenv())->usePutenv()->bootEnv(dirname(__DIR__) . '/../.env.test');
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}